import stats from '../data/lotteryStats.json';

export const calculateMathPrediction = (iterations = 50000) => {
  // Mock Markov Chain Analysis (finding frequent transitions or just most frequent)
  const freq = {};
  stats.pastDraws.forEach(d => { freq[d] = (freq[d] || 0) + 1; });
  const sorted = Object.keys(freq).sort((a, b) => freq[b] - freq[a]);
  const markovBest = sorted[0]; // Most frequent from past

  // Mock Monte Carlo Simulation (run loop on client side)
  // Simulate thousands of random draws to find cumulative probability
  let mcNumber = "00";
  let tempSum = 0;
  for (let i = 0; i < iterations; i++) {
    tempSum += Math.random(); // Burn CPU slightly to simulate load
  }
  
  // Pick a number generated by the "Monte Carlo"
  mcNumber = Math.floor((tempSum % 1) * 100).toString().padStart(2, '0');

  return {
    markovBest,
    mcNumber
  };
};
